AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for external security audit using Prowler or similar tools.

# Parameters:
#   AuditAccountId:
#     Type: String
#     Description: The AWS Account ID that will assume this role to perform security scans.

Resources:
  ExternalAuditRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "ExternalAuditRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::010928199857:root"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "AuditPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ec2:Describe*"
                  - "s3:List*"
                  - "s3:GetBucket*"
                  - "iam:Get*"
                  - "iam:List*"
                  - "config:Describe*"
                  - "cloudtrail:LookupEvents"
                  - "cloudwatch:Get*"
                  - "cloudwatch:List*"
                  - "logs:Describe*"
                  - "logs:Get*"
                  - "rds:Describe*"
                  - "kms:List*"
                  - "kms:Get*"
                Resource: "*"

Outputs:
  RoleARN:
    Description: "ARN of the audit role"
    Value: !GetAtt ExternalAuditRole.Arn
